// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// EventParticipant is the predicate function for eventparticipant builders.
type EventParticipant func(*sql.Selector)
