// Code generated by ent, DO NOT EDIT.

package nftmoment

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the nftmoment type in the database.
	Label = "nft_moment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNftID holds the string denoting the nft_id field in the database.
	FieldNftID = "nft_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldThumbnail holds the string denoting the thumbnail field in the database.
	FieldThumbnail = "thumbnail"
	// FieldLikeCount holds the string denoting the like_count field in the database.
	FieldLikeCount = "like_count"
	// FieldCommentCount holds the string denoting the comment_count field in the database.
	FieldCommentCount = "comment_count"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeEquippedAccessories holds the string denoting the equipped_accessories edge name in mutations.
	EdgeEquippedAccessories = "equipped_accessories"
	// EdgeMintedWithPass holds the string denoting the minted_with_pass edge name in mutations.
	EdgeMintedWithPass = "minted_with_pass"
	// EdgeLikes holds the string denoting the likes edge name in mutations.
	EdgeLikes = "likes"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// Table holds the table name of the nftmoment in the database.
	Table = "nft_moments"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "nft_moments"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "user_moments"
	// EquippedAccessoriesTable is the table that holds the equipped_accessories relation/edge.
	EquippedAccessoriesTable = "nft_accessories"
	// EquippedAccessoriesInverseTable is the table name for the NFTAccessory entity.
	// It exists in this package in order to avoid circular dependency with the "nftaccessory" package.
	EquippedAccessoriesInverseTable = "nft_accessories"
	// EquippedAccessoriesColumn is the table column denoting the equipped_accessories relation/edge.
	EquippedAccessoriesColumn = "nft_moment_equipped_accessories"
	// MintedWithPassTable is the table that holds the minted_with_pass relation/edge.
	MintedWithPassTable = "nft_moments"
	// MintedWithPassInverseTable is the table name for the EventPass entity.
	// It exists in this package in order to avoid circular dependency with the "eventpass" package.
	MintedWithPassInverseTable = "event_passes"
	// MintedWithPassColumn is the table column denoting the minted_with_pass relation/edge.
	MintedWithPassColumn = "event_pass_moment"
	// LikesTable is the table that holds the likes relation/edge.
	LikesTable = "likes"
	// LikesInverseTable is the table name for the Like entity.
	// It exists in this package in order to avoid circular dependency with the "like" package.
	LikesInverseTable = "likes"
	// LikesColumn is the table column denoting the likes relation/edge.
	LikesColumn = "nft_moment_likes"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "comments"
	// CommentsInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	CommentsInverseTable = "comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "nft_moment_comments"
)

// Columns holds all SQL columns for nftmoment fields.
var Columns = []string{
	FieldID,
	FieldNftID,
	FieldName,
	FieldDescription,
	FieldThumbnail,
	FieldLikeCount,
	FieldCommentCount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "nft_moments"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"event_pass_moment",
	"user_moments",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultLikeCount holds the default value on creation for the "like_count" field.
	DefaultLikeCount int
	// DefaultCommentCount holds the default value on creation for the "comment_count" field.
	DefaultCommentCount int
)

// OrderOption defines the ordering options for the NFTMoment queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNftID orders the results by the nft_id field.
func ByNftID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNftID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByThumbnail orders the results by the thumbnail field.
func ByThumbnail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThumbnail, opts...).ToFunc()
}

// ByLikeCount orders the results by the like_count field.
func ByLikeCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLikeCount, opts...).ToFunc()
}

// ByCommentCount orders the results by the comment_count field.
func ByCommentCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommentCount, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByEquippedAccessoriesCount orders the results by equipped_accessories count.
func ByEquippedAccessoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEquippedAccessoriesStep(), opts...)
	}
}

// ByEquippedAccessories orders the results by equipped_accessories terms.
func ByEquippedAccessories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEquippedAccessoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByMintedWithPassField orders the results by minted_with_pass field.
func ByMintedWithPassField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMintedWithPassStep(), sql.OrderByField(field, opts...))
	}
}

// ByLikesCount orders the results by likes count.
func ByLikesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLikesStep(), opts...)
	}
}

// ByLikes orders the results by likes terms.
func ByLikes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLikesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newEquippedAccessoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EquippedAccessoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EquippedAccessoriesTable, EquippedAccessoriesColumn),
	)
}
func newMintedWithPassStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MintedWithPassInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, MintedWithPassTable, MintedWithPassColumn),
	)
}
func newLikesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LikesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LikesTable, LikesColumn),
	)
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CommentsTable, CommentsColumn),
	)
}
