// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/event"
	"backend/ent/eventparticipant"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventParticipantCreate is the builder for creating a EventParticipant entity.
type EventParticipantCreate struct {
	config
	mutation *EventParticipantMutation
	hooks    []Hook
}

// SetUserAddress sets the "userAddress" field.
func (_c *EventParticipantCreate) SetUserAddress(v string) *EventParticipantCreate {
	_c.mutation.SetUserAddress(v)
	return _c
}

// SetNillableUserAddress sets the "userAddress" field if the given value is not nil.
func (_c *EventParticipantCreate) SetNillableUserAddress(v *string) *EventParticipantCreate {
	if v != nil {
		_c.SetUserAddress(*v)
	}
	return _c
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_c *EventParticipantCreate) SetEventID(id int) *EventParticipantCreate {
	_c.mutation.SetEventID(id)
	return _c
}

// SetEvent sets the "event" edge to the Event entity.
func (_c *EventParticipantCreate) SetEvent(v *Event) *EventParticipantCreate {
	return _c.SetEventID(v.ID)
}

// Mutation returns the EventParticipantMutation object of the builder.
func (_c *EventParticipantCreate) Mutation() *EventParticipantMutation {
	return _c.mutation
}

// Save creates the EventParticipant in the database.
func (_c *EventParticipantCreate) Save(ctx context.Context) (*EventParticipant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *EventParticipantCreate) SaveX(ctx context.Context) *EventParticipant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventParticipantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventParticipantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *EventParticipantCreate) defaults() {
	if _, ok := _c.mutation.UserAddress(); !ok {
		v := eventparticipant.DefaultUserAddress
		_c.mutation.SetUserAddress(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *EventParticipantCreate) check() error {
	if _, ok := _c.mutation.UserAddress(); !ok {
		return &ValidationError{Name: "userAddress", err: errors.New(`ent: missing required field "EventParticipant.userAddress"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "EventParticipant.event"`)}
	}
	return nil
}

func (_c *EventParticipantCreate) sqlSave(ctx context.Context) (*EventParticipant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *EventParticipantCreate) createSpec() (*EventParticipant, *sqlgraph.CreateSpec) {
	var (
		_node = &EventParticipant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(eventparticipant.Table, sqlgraph.NewFieldSpec(eventparticipant.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserAddress(); ok {
		_spec.SetField(eventparticipant.FieldUserAddress, field.TypeString, value)
		_node.UserAddress = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventparticipant.EventTable,
			Columns: []string{eventparticipant.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.event_event_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// EventParticipantCreateBulk is the builder for creating many EventParticipant entities in bulk.
type EventParticipantCreateBulk struct {
	config
	err      error
	builders []*EventParticipantCreate
}

// Save creates the EventParticipant entities in the database.
func (_c *EventParticipantCreateBulk) Save(ctx context.Context) ([]*EventParticipant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*EventParticipant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventParticipantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *EventParticipantCreateBulk) SaveX(ctx context.Context) []*EventParticipant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *EventParticipantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *EventParticipantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
