// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/event"
	"backend/ent/eventparticipant"
	"backend/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventParticipantUpdate is the builder for updating EventParticipant entities.
type EventParticipantUpdate struct {
	config
	hooks    []Hook
	mutation *EventParticipantMutation
}

// Where appends a list predicates to the EventParticipantUpdate builder.
func (_u *EventParticipantUpdate) Where(ps ...predicate.EventParticipant) *EventParticipantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserAddress sets the "userAddress" field.
func (_u *EventParticipantUpdate) SetUserAddress(v string) *EventParticipantUpdate {
	_u.mutation.SetUserAddress(v)
	return _u
}

// SetNillableUserAddress sets the "userAddress" field if the given value is not nil.
func (_u *EventParticipantUpdate) SetNillableUserAddress(v *string) *EventParticipantUpdate {
	if v != nil {
		_u.SetUserAddress(*v)
	}
	return _u
}

// SetIsCheckedIn sets the "isCheckedIn" field.
func (_u *EventParticipantUpdate) SetIsCheckedIn(v bool) *EventParticipantUpdate {
	_u.mutation.SetIsCheckedIn(v)
	return _u
}

// SetNillableIsCheckedIn sets the "isCheckedIn" field if the given value is not nil.
func (_u *EventParticipantUpdate) SetNillableIsCheckedIn(v *bool) *EventParticipantUpdate {
	if v != nil {
		_u.SetIsCheckedIn(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *EventParticipantUpdate) SetEventID(id int) *EventParticipantUpdate {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *EventParticipantUpdate) SetEvent(v *Event) *EventParticipantUpdate {
	return _u.SetEventID(v.ID)
}

// Mutation returns the EventParticipantMutation object of the builder.
func (_u *EventParticipantUpdate) Mutation() *EventParticipantMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *EventParticipantUpdate) ClearEvent() *EventParticipantUpdate {
	_u.mutation.ClearEvent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EventParticipantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventParticipantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EventParticipantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventParticipantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventParticipantUpdate) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventParticipant.event"`)
	}
	return nil
}

func (_u *EventParticipantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventparticipant.Table, eventparticipant.Columns, sqlgraph.NewFieldSpec(eventparticipant.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserAddress(); ok {
		_spec.SetField(eventparticipant.FieldUserAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCheckedIn(); ok {
		_spec.SetField(eventparticipant.FieldIsCheckedIn, field.TypeBool, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventparticipant.EventTable,
			Columns: []string{eventparticipant.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventparticipant.EventTable,
			Columns: []string{eventparticipant.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventparticipant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EventParticipantUpdateOne is the builder for updating a single EventParticipant entity.
type EventParticipantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventParticipantMutation
}

// SetUserAddress sets the "userAddress" field.
func (_u *EventParticipantUpdateOne) SetUserAddress(v string) *EventParticipantUpdateOne {
	_u.mutation.SetUserAddress(v)
	return _u
}

// SetNillableUserAddress sets the "userAddress" field if the given value is not nil.
func (_u *EventParticipantUpdateOne) SetNillableUserAddress(v *string) *EventParticipantUpdateOne {
	if v != nil {
		_u.SetUserAddress(*v)
	}
	return _u
}

// SetIsCheckedIn sets the "isCheckedIn" field.
func (_u *EventParticipantUpdateOne) SetIsCheckedIn(v bool) *EventParticipantUpdateOne {
	_u.mutation.SetIsCheckedIn(v)
	return _u
}

// SetNillableIsCheckedIn sets the "isCheckedIn" field if the given value is not nil.
func (_u *EventParticipantUpdateOne) SetNillableIsCheckedIn(v *bool) *EventParticipantUpdateOne {
	if v != nil {
		_u.SetIsCheckedIn(*v)
	}
	return _u
}

// SetEventID sets the "event" edge to the Event entity by ID.
func (_u *EventParticipantUpdateOne) SetEventID(id int) *EventParticipantUpdateOne {
	_u.mutation.SetEventID(id)
	return _u
}

// SetEvent sets the "event" edge to the Event entity.
func (_u *EventParticipantUpdateOne) SetEvent(v *Event) *EventParticipantUpdateOne {
	return _u.SetEventID(v.ID)
}

// Mutation returns the EventParticipantMutation object of the builder.
func (_u *EventParticipantUpdateOne) Mutation() *EventParticipantMutation {
	return _u.mutation
}

// ClearEvent clears the "event" edge to the Event entity.
func (_u *EventParticipantUpdateOne) ClearEvent() *EventParticipantUpdateOne {
	_u.mutation.ClearEvent()
	return _u
}

// Where appends a list predicates to the EventParticipantUpdate builder.
func (_u *EventParticipantUpdateOne) Where(ps ...predicate.EventParticipant) *EventParticipantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EventParticipantUpdateOne) Select(field string, fields ...string) *EventParticipantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EventParticipant entity.
func (_u *EventParticipantUpdateOne) Save(ctx context.Context) (*EventParticipant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EventParticipantUpdateOne) SaveX(ctx context.Context) *EventParticipant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EventParticipantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EventParticipantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EventParticipantUpdateOne) check() error {
	if _u.mutation.EventCleared() && len(_u.mutation.EventIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EventParticipant.event"`)
	}
	return nil
}

func (_u *EventParticipantUpdateOne) sqlSave(ctx context.Context) (_node *EventParticipant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(eventparticipant.Table, eventparticipant.Columns, sqlgraph.NewFieldSpec(eventparticipant.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EventParticipant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventparticipant.FieldID)
		for _, f := range fields {
			if !eventparticipant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != eventparticipant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserAddress(); ok {
		_spec.SetField(eventparticipant.FieldUserAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsCheckedIn(); ok {
		_spec.SetField(eventparticipant.FieldIsCheckedIn, field.TypeBool, value)
	}
	if _u.mutation.EventCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventparticipant.EventTable,
			Columns: []string{eventparticipant.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   eventparticipant.EventTable,
			Columns: []string{eventparticipant.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EventParticipant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{eventparticipant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
