// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/event"
	"backend/ent/partner"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PartnerCreate is the builder for creating a Partner entity.
type PartnerCreate struct {
	config
	mutation *PartnerMutation
	hooks    []Hook
}

// SetAddress sets the "address" field.
func (_c *PartnerCreate) SetAddress(v string) *PartnerCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PartnerCreate) SetName(v string) *PartnerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *PartnerCreate) SetNillableName(v *string) *PartnerCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *PartnerCreate) SetDescription(v string) *PartnerCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PartnerCreate) SetNillableDescription(v *string) *PartnerCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *PartnerCreate) SetEmail(v string) *PartnerCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *PartnerCreate) SetNillableEmail(v *string) *PartnerCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetImage sets the "image" field.
func (_c *PartnerCreate) SetImage(v string) *PartnerCreate {
	_c.mutation.SetImage(v)
	return _c
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_c *PartnerCreate) SetNillableImage(v *string) *PartnerCreate {
	if v != nil {
		_c.SetImage(*v)
	}
	return _c
}

// AddPartnerAddresIDs adds the "partner_address" edge to the Event entity by IDs.
func (_c *PartnerCreate) AddPartnerAddresIDs(ids ...int) *PartnerCreate {
	_c.mutation.AddPartnerAddresIDs(ids...)
	return _c
}

// AddPartnerAddress adds the "partner_address" edges to the Event entity.
func (_c *PartnerCreate) AddPartnerAddress(v ...*Event) *PartnerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPartnerAddresIDs(ids...)
}

// Mutation returns the PartnerMutation object of the builder.
func (_c *PartnerCreate) Mutation() *PartnerMutation {
	return _c.mutation
}

// Save creates the Partner in the database.
func (_c *PartnerCreate) Save(ctx context.Context) (*Partner, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PartnerCreate) SaveX(ctx context.Context) *Partner {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PartnerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PartnerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PartnerCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := partner.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := partner.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Email(); !ok {
		v := partner.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.Image(); !ok {
		v := partner.DefaultImage
		_c.mutation.SetImage(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PartnerCreate) check() error {
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Partner.address"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Partner.name"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Partner.description"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Partner.email"`)}
	}
	if _, ok := _c.mutation.Image(); !ok {
		return &ValidationError{Name: "image", err: errors.New(`ent: missing required field "Partner.image"`)}
	}
	return nil
}

func (_c *PartnerCreate) sqlSave(ctx context.Context) (*Partner, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PartnerCreate) createSpec() (*Partner, *sqlgraph.CreateSpec) {
	var (
		_node = &Partner{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(partner.Table, sqlgraph.NewFieldSpec(partner.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(partner.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(partner.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(partner.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(partner.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Image(); ok {
		_spec.SetField(partner.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if nodes := _c.mutation.PartnerAddressIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   partner.PartnerAddressTable,
			Columns: []string{partner.PartnerAddressColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PartnerCreateBulk is the builder for creating many Partner entities in bulk.
type PartnerCreateBulk struct {
	config
	err      error
	builders []*PartnerCreate
}

// Save creates the Partner entities in the database.
func (_c *PartnerCreateBulk) Save(ctx context.Context) ([]*Partner, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Partner, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PartnerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PartnerCreateBulk) SaveX(ctx context.Context) []*Partner {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PartnerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PartnerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
