// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/partner"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Partner is the model entity for the Partner schema.
type Partner struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Address holds the value of the "address" field.
	Address string `json:"address,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Image holds the value of the "image" field.
	Image string `json:"image,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PartnerQuery when eager-loading is set.
	Edges        PartnerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PartnerEdges holds the relations/edges for other nodes in the graph.
type PartnerEdges struct {
	// PartnerAddress holds the value of the partner_address edge.
	PartnerAddress []*Event `json:"partner_address,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PartnerAddressOrErr returns the PartnerAddress value or an error if the edge
// was not loaded in eager-loading.
func (e PartnerEdges) PartnerAddressOrErr() ([]*Event, error) {
	if e.loadedTypes[0] {
		return e.PartnerAddress, nil
	}
	return nil, &NotLoadedError{edge: "partner_address"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Partner) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case partner.FieldID:
			values[i] = new(sql.NullInt64)
		case partner.FieldAddress, partner.FieldName, partner.FieldDescription, partner.FieldEmail, partner.FieldImage:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Partner fields.
func (_m *Partner) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case partner.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case partner.FieldAddress:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field address", values[i])
			} else if value.Valid {
				_m.Address = value.String
			}
		case partner.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case partner.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case partner.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case partner.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				_m.Image = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Partner.
// This includes values selected through modifiers, order, etc.
func (_m *Partner) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPartnerAddress queries the "partner_address" edge of the Partner entity.
func (_m *Partner) QueryPartnerAddress() *EventQuery {
	return NewPartnerClient(_m.config).QueryPartnerAddress(_m)
}

// Update returns a builder for updating this Partner.
// Note that you need to call Partner.Unwrap() before calling this method if this Partner
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Partner) Update() *PartnerUpdateOne {
	return NewPartnerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Partner entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Partner) Unwrap() *Partner {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Partner is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Partner) String() string {
	var builder strings.Builder
	builder.WriteString("Partner(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("address=")
	builder.WriteString(_m.Address)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(_m.Image)
	builder.WriteByte(')')
	return builder.String()
}

// Partners is a parsable slice of Partner.
type Partners []*Partner
