// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/event"
	"backend/ent/eventparticipant"
	"backend/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	eventFields := schema.Event{}.Fields()
	_ = eventFields
	// eventDescBrandAddress is the schema descriptor for brandAddress field.
	eventDescBrandAddress := eventFields[1].Descriptor()
	// event.DefaultBrandAddress holds the default value on creation for the brandAddress field.
	event.DefaultBrandAddress = eventDescBrandAddress.Default.(string)
	eventparticipantFields := schema.EventParticipant{}.Fields()
	_ = eventparticipantFields
	// eventparticipantDescUserAddress is the schema descriptor for userAddress field.
	eventparticipantDescUserAddress := eventparticipantFields[0].Descriptor()
	// eventparticipant.DefaultUserAddress holds the default value on creation for the userAddress field.
	eventparticipant.DefaultUserAddress = eventparticipantDescUserAddress.Default.(string)
}
